name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # ubuntu-latest github runner 사용
    runs-on: ubuntu-latest

    steps:
      # repository checkout
      - uses: actions/checkout@v4

      # tonistiigi/binfmt 이미지를 이용해 qemu 설치
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      
      # docker buildx 설치
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2
              
      # buildx 명령어로 amd64, arm64 아키텍처 이미지 빌드 
      - name: Build the Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t minecraft-playerlist:$(date +%s)
