name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 코드 가져오기
      uses: actions/checkout@v4

    - name: Buildx 설정
      uses: docker/setup-buildx-action@v2

      
    - name: Build the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: minecraft-playerlist:$(date +%s)
