name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 코드 가져오기
      uses: actions/checkout@v4

    - name: Buildx 설정
      uses: docker/setup-buildx-action@v2

    - name: Set build timestamp
      id: timestamp
      run: echo "TAG=$(date +%s)" >> $GITHUB_ENV
      
    - name: Build the Docker image
      run: docker buildx --platform linux/amd64,linux/arm64 -t minecraft-playerlist:$(date +%s)
