name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    # tonistiigi/binfmt 이미지를 이용해 qemu 설치
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
  
    # docker buildx 설치
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 --tag minecraft-playerlist:$(date +%s) --push .
