name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker 이미지 태그를 입력하세요 (예: v1.0.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # QEMU를 사용하여 멀티 아키텍처 지원
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      
      # Buildx 설정
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      # GHCR에 로그인 (GHCR 토큰은 repository secret에 등록되어 있어야 함)
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 멀티 아키텍처 이미지 빌드 및 GHCR에 푸시
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          provenance: false
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}
          platforms: |
            linux/amd64
            linux/arm64